export const questionsJSON = {
  categories: [
    {
      id: "js_basics",
      name: "JavaScript Basics",
      questions: [
        {
          id: "q1",
          question:
            "What is the correct syntax for referring to an external script called 'script.js'?",
          options: [
            "A. <script name='script.js'>",
            "B. <script href='script.js'>",
            "C. <script src='script.js'>",
            "D. <script file='script.js'>",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "q2",
          question: "Which company developed JavaScript?",
          options: ["A. Microsoft", "B. Netscape", "C. Google", "D. Mozilla"],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "q3",
          question: "Which symbol is used for comments in JavaScript?",
          options: ["A. //", "B. <!-- -->", "C. #", "D. **"],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "q4",
          question: "How do you declare a JavaScript variable?",
          options: [
            "A. var car;",
            "B. let car;",
            "C. const car;",
            "D. All of the above",
          ],
          correctAnswer: "D",
          timeLimit: 10,
        },
        {
          id: "q5",
          question:
            "Which method is used to convert a JSON string to an object?",
          options: [
            "A. JSON.parse()",
            "B. JSON.stringify()",
            "C. JSON.convert()",
            "D. JSON.objectify()",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "q6",
          question: "Which operator is used to assign a value to a variable?",
          options: ["A. *", "B. =", "C. -", "D. +"],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "q7",
          question: "How do you write 'Hello World' in an alert box?",
          options: [
            "A. msg('Hello World');",
            "B. alert('Hello World');",
            "C. msgBox('Hello World');",
            "D. alertBox('Hello World');",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "q8",
          question: "Which keyword is used to define a function in JavaScript?",
          options: ["A. function", "B. def", "C. func", "D. void"],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "q9",
          question: "How do you round the number 7.25 to the nearest integer?",
          options: [
            "A. Math.round(7.25)",
            "B. round(7.25)",
            "C. Math.rnd(7.25)",
            "D. rnd(7.25)",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "q10",
          question:
            "What is the correct JavaScript syntax to change the content of an HTML element?",
          options: [
            "A. document.getElementById('demo').innerHTML = 'Hello';",
            "B. #demo.innerHTML = 'Hello';",
            "C. document.querySelector('demo').text = 'Hello';",
            "D. document.getElement('demo') = 'Hello';",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "react_advanced",
      name: "React Advanced",
      questions: [
        {
          id: "r1",
          question: "What hook is used for performance optimization in React?",
          options: [
            "A. useState",
            "B. useEffect",
            "C. useMemo",
            "D. useCallback",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "r2",
          question: "What does React.lazy() help with?",
          options: [
            "A. Lazy state updates",
            "B. Lazy rendering of components",
            "C. Code splitting",
            "D. Avoiding re-renders",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "r3",
          question:
            "Which hook is used to manage side effects in functional components?",
          options: [
            "A. useEffect",
            "B. useMemo",
            "C. useCallback",
            "D. useReducer",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "r4",
          question: "How can you improve performance in React lists?",
          options: [
            "A. By using unique keys",
            "B. By avoiding maps",
            "C. By using for loops",
            "D. By memoizing the list",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "r5",
          question: "What is the use of React.Fragment?",
          options: [
            "A. To style components",
            "B. To return multiple elements",
            "C. To lazy load components",
            "D. None of the above",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "r6",
          question: "What is React.StrictMode used for?",
          options: [
            "A. Avoid unnecessary re-renders",
            "B. Highlight potential issues",
            "C. Prevent rendering errors",
            "D. Add security",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "r7",
          question: "What does `useReducer` hook do?",
          options: [
            "A. It’s an alternative to useState",
            "B. It’s used to reduce the size of components",
            "C. It handles form validation",
            "D. It creates child reducers",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "r8",
          question:
            "Which hook helps in preventing re-rendering of child components?",
          options: [
            "A. useEffect",
            "B. useMemo",
            "C. useCallback",
            "D. React.memo",
          ],
          correctAnswer: "D",
          timeLimit: 10,
        },
        {
          id: "r9",
          question: "How does Context API help in React?",
          options: [
            "A. State Management",
            "B. Styling",
            "C. Routing",
            "D. Fetching API",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "r10",
          question: "How do you enable code-splitting in React?",
          options: [
            "A. Using React.lazy",
            "B. Using Webpack",
            "C. Using dynamic import()",
            "D. All of the above",
          ],
          correctAnswer: "D",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "angular",
      name: "Angular",
      questions: [
        {
          id: "a1",
          question: "What is Angular primarily used for?",
          options: [
            "A. Mobile Apps",
            "B. Backend Services",
            "C. Web Applications",
            "D. Game Development",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "a2",
          question: "Which file defines the root module in Angular?",
          options: [
            "A. main.ts",
            "B. app.module.ts",
            "C. index.html",
            "D. angular.json",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "a3",
          question: "Which decorator is used to create a component?",
          options: [
            "A. @Injectable",
            "B. @NgModule",
            "C. @Component",
            "D. @Input",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "a4",
          question: "Which directive is used for conditional rendering?",
          options: ["A. *ngIf", "B. *ngFor", "C. ngModel", "D. ngBind"],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "a5",
          question: "What is a service in Angular?",
          options: [
            "A. A type of component",
            "B. A class for business logic",
            "C. A template engine",
            "D. A directive",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "a6",
          question:
            "What is the Angular CLI command to create a new component?",
          options: [
            "A. ng new component",
            "B. ng generate component",
            "C. ng create component",
            "D. ng make component",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "a7",
          question:
            "Which lifecycle hook runs after the component’s view has been fully initialized?",
          options: [
            "A. ngOnInit",
            "B. ngAfterViewInit",
            "C. ngOnChanges",
            "D. ngDoCheck",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "a8",
          question:
            "Which file is used to configure global settings in Angular?",
          options: [
            "A. app.module.ts",
            "B. angular.json",
            "C. main.ts",
            "D. tsconfig.json",
          ],
          correctAnswer: "B",
          timeLimit: 10,
        },
        {
          id: "a9",
          question: "What is data binding in Angular?",
          options: [
            "A. Binding CSS",
            "B. Binding forms",
            "C. Connecting data and view",
            "D. Routing data",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "a10",
          question: "Which module is used for routing in Angular?",
          options: [
            "A. FormsModule",
            "B. BrowserModule",
            "C. RouterModule",
            "D. HttpClientModule",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
      ],
    },
    {
      id: "flutter",
      name: "Flutter",
      questions: [
        {
          id: "f1",
          question: "What language is Flutter based on?",
          options: ["A. Kotlin", "B. JavaScript", "C. Dart", "D. Swift"],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "f2",
          question: "Which widget is used for layouts in Flutter?",
          options: ["A. Column", "B. Stack", "C. Row", "D. All of the above"],
          correctAnswer: "D",
          timeLimit: 10,
        },
        {
          id: "f3",
          question: "What is the command to create a new Flutter project?",
          options: [
            "A. flutter create project_name",
            "B. flutter init project",
            "C. flutter new",
            "D. flutter generate",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "f4",
          question: "Which company created Flutter?",
          options: ["A. Facebook", "B. Microsoft", "C. Google", "D. Apple"],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "f5",
          question: "What is a StatelessWidget?",
          options: [
            "A. A widget that doesn’t store state",
            "B. A widget with animations",
            "C. A widget that connects to API",
            "D. A widget for layout",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "f6",
          question: "Which command runs the Flutter app?",
          options: [
            "A. flutter go",
            "B. flutter start",
            "C. flutter run",
            "D. flutter launch",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "f7",
          question: "Which file is the entry point of a Flutter app?",
          options: [
            "A. main.dart",
            "B. app.dart",
            "C. home.dart",
            "D. start.dart",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "f8",
          question: "What is the pubspec.yaml file used for?",
          options: [
            "A. Styling",
            "B. Routing",
            "C. Managing dependencies",
            "D. Localization",
          ],
          correctAnswer: "C",
          timeLimit: 10,
        },
        {
          id: "f9",
          question: "How do you hot reload in Flutter?",
          options: [
            "A. By pressing 'r'",
            "B. By restarting the IDE",
            "C. Via flutter refresh",
            "D. Using 'flutter reload' command",
          ],
          correctAnswer: "A",
          timeLimit: 10,
        },
        {
          id: "f10",
          question: "What layout allows widgets to overlap each other?",
          options: ["A. Column", "B. Row", "C. Stack", "D. ListView"],
          correctAnswer: "C",
          timeLimit: 10,
        },
      ],
    },
  ],
};
